#!/usr/bin/env node

/**
 * Gmail Draft Helper
 *
 * Creates Gmail drafts from outreach email objects generated by full-pipeline.js.
 * Drafts land in your Gmail Drafts folder ready to review and send.
 *
 * --- Setup ---
 * Option A — Environment variables (CI / headless):
 *   GMAIL_CLIENT_ID, GMAIL_CLIENT_SECRET, GMAIL_REFRESH_TOKEN
 *   GMAIL_FROM (optional — defaults to the authenticated account's address)
 *
 * Option B — OAuth credentials file (interactive first-time setup):
 *   1. Go to https://console.cloud.google.com → APIs & Services → Credentials
 *   2. Create an OAuth 2.0 Client ID (Desktop app)
 *   3. Download the JSON and save it to ~/.kspf/gmail-credentials.json
 *   4. Run:  node gmail-draft.js --setup
 *   5. Paste the URL into your browser, authorise, paste the code back
 *
 * After setup the token is saved to ~/.kspf/gmail-token.json and reused
 * on every subsequent run.
 */

import { google } from 'googleapis';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { createInterface } from 'readline';
import { homedir } from 'os';
import { join } from 'path';
import chalk from 'chalk';

// ------------------------------------------------------------------ paths ---

const CONFIG_DIR = join(homedir(), '.kspf');
const CREDENTIALS_PATH = join(CONFIG_DIR, 'gmail-credentials.json');
const TOKEN_PATH = join(CONFIG_DIR, 'gmail-token.json');

// Only the compose scope — we never read existing emails
const SCOPES = ['https://www.googleapis.com/auth/gmail.compose'];

// --------------------------------------------------------- auth helpers ----

function buildOAuth2Client(clientId, clientSecret, redirectUri) {
  return new google.auth.OAuth2(clientId, clientSecret, redirectUri);
}

/**
 * Returns an authenticated OAuth2 client, or null if credentials are missing.
 */
function getAuth() {
  // Option A: environment variables
  const envId = process.env.GMAIL_CLIENT_ID;
  const envSecret = process.env.GMAIL_CLIENT_SECRET;
  const envRefresh = process.env.GMAIL_REFRESH_TOKEN;

  if (envId && envSecret && envRefresh) {
    const client = buildOAuth2Client(envId, envSecret, 'urn:ietf:wg:oauth:2.0:oob');
    client.setCredentials({
      refresh_token: envRefresh,
      access_token: process.env.GMAIL_ACCESS_TOKEN || undefined
    });
    return client;
  }

  // Option B: credentials file + saved token
  if (existsSync(CREDENTIALS_PATH) && existsSync(TOKEN_PATH)) {
    const creds = JSON.parse(readFileSync(CREDENTIALS_PATH, 'utf-8'));
    const { client_id, client_secret, redirect_uris } = creds.installed || creds.web;
    const client = buildOAuth2Client(client_id, client_secret, redirect_uris[0]);
    client.setCredentials(JSON.parse(readFileSync(TOKEN_PATH, 'utf-8')));
    return client;
  }

  return null;
}

// ------------------------------------------------- MIME message builder ----

/**
 * Encodes an outreach email as a base64url RFC 2822 message suitable for the
 * Gmail API drafts.create endpoint.
 */
function buildRawMessage({ to, subject, body, from }) {
  const lines = [
    `From: ${from}`,
    `To: ${to}`,
    `Subject: ${subject}`,
    'MIME-Version: 1.0',
    'Content-Type: text/plain; charset=utf-8',
    '',
    body
  ];
  return Buffer.from(lines.join('\r\n')).toString('base64url');
}

// ------------------------------------------------- public API ----------- ---

/**
 * Creates Gmail drafts for all emails that have a `to` address.
 *
 * @param {Array<{to: string, subject: string, body: string}>} emails
 * @returns {{ created: number, failed: number, skipped: number, configured: boolean }}
 */
export async function createGmailDrafts(emails) {
  const auth = getAuth();

  if (!auth) {
    return { created: 0, failed: 0, skipped: emails.length, configured: false };
  }

  const gmail = google.gmail({ version: 'v1', auth });

  // Resolve sender address: env override → authenticated Gmail address → fallback
  let fromAddress = process.env.GMAIL_FROM;
  if (!fromAddress) {
    try {
      const profile = await gmail.users.getProfile({ userId: 'me' });
      fromAddress = profile.data.emailAddress;
    } catch {
      fromAddress = 'studio@kspf.au';
    }
  }

  let created = 0;
  let failed = 0;
  let skipped = 0;

  for (const email of emails) {
    if (!email.to) {
      skipped++;
      continue;
    }

    try {
      const raw = buildRawMessage({
        to: email.to,
        subject: email.subject,
        body: email.body,
        from: fromAddress
      });

      await gmail.users.drafts.create({
        userId: 'me',
        requestBody: { message: { raw } }
      });

      created++;
    } catch (err) {
      failed++;
      console.error(chalk.red(`  ✗ Draft failed for ${email.to}: ${err.message}`));
    }
  }

  return { created, failed, skipped, configured: true };
}

// ------------------------------------------ interactive setup command ----

async function runSetup() {
  console.log(chalk.bold.blue('\n🔐 Gmail OAuth2 Setup\n'));

  if (!existsSync(CREDENTIALS_PATH)) {
    console.log(chalk.red('No credentials file found at:'));
    console.log(chalk.gray(`  ${CREDENTIALS_PATH}\n`));
    console.log('Steps to create one:');
    console.log('  1. Go to https://console.cloud.google.com');
    console.log('  2. Create a project → APIs & Services → Enable Gmail API');
    console.log('  3. Credentials → Create OAuth 2.0 Client ID (Desktop app)');
    console.log('  4. Download JSON → save to:', CREDENTIALS_PATH);
    console.log('\nThen re-run:  node gmail-draft.js --setup\n');
    process.exit(1);
  }

  const creds = JSON.parse(readFileSync(CREDENTIALS_PATH, 'utf-8'));
  const { client_id, client_secret, redirect_uris } = creds.installed || creds.web;
  const client = buildOAuth2Client(client_id, client_secret, redirect_uris[0]);

  const authUrl = client.generateAuthUrl({ access_type: 'offline', scope: SCOPES });
  console.log(chalk.cyan('Open this URL in your browser:\n'));
  console.log(authUrl);
  console.log();

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const code = await new Promise(resolve => rl.question('Paste the authorisation code here: ', resolve));
  rl.close();

  const { tokens } = await client.getToken(code.trim());
  client.setCredentials(tokens);

  if (!existsSync(CONFIG_DIR)) mkdirSync(CONFIG_DIR, { recursive: true });
  writeFileSync(TOKEN_PATH, JSON.stringify(tokens, null, 2));
  console.log(chalk.green(`\n✅ Token saved to ${TOKEN_PATH}`));
  console.log(chalk.gray('Gmail draft sync is now enabled for full-pipeline.js\n'));
}

// ----------------------------------- print setup instructions (no creds) ---

export function printSetupInstructions() {
  console.log(chalk.yellow('\n  ⚠️  Gmail drafts skipped — credentials not configured.'));
  console.log(chalk.gray('  To enable Gmail draft sync, choose one of:\n'));
  console.log(chalk.gray('  Option A — Environment variables:'));
  console.log(chalk.gray('    GMAIL_CLIENT_ID=...'));
  console.log(chalk.gray('    GMAIL_CLIENT_SECRET=...'));
  console.log(chalk.gray('    GMAIL_REFRESH_TOKEN=...'));
  console.log(chalk.gray('    GMAIL_FROM=studio@kspf.au  (optional — defaults to authed account)\n'));
  console.log(chalk.gray('  Option B — Interactive setup (one-time):'));
  console.log(chalk.gray('    node tools/website-auditor/gmail-draft.js --setup\n'));
}

// ------------------------------------------------------ CLI entry point ---

if (process.argv[1] && process.argv[1].endsWith('gmail-draft.js')) {
  if (process.argv.includes('--setup')) {
    runSetup().catch(err => {
      console.error(chalk.red(err.message));
      process.exit(1);
    });
  } else {
    console.log(chalk.gray('Usage:  node gmail-draft.js --setup'));
    console.log(chalk.gray('        (run this once to authorise Gmail access)\n'));
  }
}
